### ISSUE TITLE
When Fabric workspace name contains a space downloading of metadata does not work

### ISSUE THREAD

**Issue by insightgrantkrieger** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#111]
When Fabric workspace name contains a space downloading of metadata does not work. Please see DownloadMetaFiles method in utils.py (dbt_wrapper)

**Comment by KRodriguez-Insight** [comment]
Replicated the issue, and found that when the workspace name has a space example "My workspace" , the azure storage adapter does not support the workspace name in the URL , Resulted a  http 404 , stating lakehouse not found in workspace error. 

To overcome this issue , the following fix is proposed to pass GUID, and this works in my testing 

![image](https://github.com/user-attachments/assets/5e805499-83e8-47b6-8a77-320d595b3652)

@insightgrantkrieger

**Comment by annstephyjose** [comment]
tested and working fine
