### ISSUE TITLE
Alter wrapper to cater for tag build and publish

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#118]

**Comment by insightgrantkrieger** [comment]
added a switch --select to align with DBT
example will be --select tag:mytag

**Comment by insightgrantkrieger** [comment]
Will developer test tomorrow am and hand over for official testing tomorrow

**Comment by insightgrantkrieger** [comment]
Completed and tested all good
