### ISSUE TITLE
Support for schema enabled Lakehouses

### ISSUE THREAD

**Issue by avinvagel** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#123]
The `metadata_my_project_extract` notebooks fails is the target lakehouse has the in-preview schemas enabled.

The:  `List Schemas Macro Export` cell will return the schema in the format: `<workspacename>.<lakehousename>.<schema>` instead of: `<schema>`

eg: `myworkspace.mylakehouse.dbo` instead of: `dbo`

The `List Relations` cell will then fail trying to execute `sql = f"show table extended in {row['namespace']} like '*'"` trying to execute: `show table extended in myworkspace.mylakehouse.dbo.mylakehouse.dbo`

**Comment by insightgrantkrieger** [comment]
This is on hold and we will discuss at the stand up

**Comment by cheinamann** [comment]
After discussion in our weekly meeting, we have decided to park this. As 1. this is a preview feature and a lot of the API's a database spark functions don't work. 2. Having schemas included does not follow the standard hive format for delta.
