### ISSUE TITLE
Review Lowercase / uppercase checks and case naming convention in framework

### ISSUE THREAD

**Issue by KRodriguez-Insight** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#129]
- Consider having namespace comparison in lower case. similar to issue #94 
- Additionally some of the naming convention related to notebook are inconsistent (to consider lower case naming convention and query generation in note book.

![image](https://github.com/user-attachments/assets/fa1a852d-6166-44d5-b908-3082b6fbabb1)

**Comment by KRodriguez-Insight** [comment]
The intent of this ticket was to standardize the SQL artifact naming convention on the following 

1. Schema and table name printed in log ( The logs are generated by the DBT modules and not from FabricSparknb modules).
2. Testing the changes to convert the sql generated in notebook to lower case. 

Require some more time to test the changes , would like to move this to next release

**Comment by KRodriguez-Insight** [comment]
Changes include conversion if SQL syntax in model notebook to lower case

![image](https://github.com/user-attachments/assets/59c9ecd5-2602-4e4e-b6b0-505e65c8dc81)

![image](https://github.com/user-attachments/assets/583b1657-2cae-4cd3-9eef-737cdba54af1)

**Comment by insightgrantkrieger** [comment]
Closed user must write the correct case in the model
