### ISSUE TITLE
Enhance the automatic git action scripts on pull into dev and main branch to actually deploy and run a test project

### ISSUE THREAD

**Issue by insightgrantkrieger** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#130]
Enhance the automatic git action scripts on pull into dev and main branch to actually deploy and run a test project. We need to automate more of the testing process as this is consuming time.

Things to note: 
A Fabric workspace is required for this. 
Datalakes should have all objects removed prior to starting
Fabric Capacity should be stopped on completion
A complex project should be used that tests a wide range of features. EG ptfproj in samples

**Comment by KRodriguez-Insight** [comment]
Update : Service request (Request Raised by Ann) for a Dev workspace will take 3 weeks due to some limitations on capacity.
As an alternative we can  created a new workspace in another tenant, Test Repo and Service principal has been created, and will continue to test.

**Comment by KRodriguez-Insight** [comment]
Update on Testing using Service Principal. 

- Setup and app with relevant permissions, as show below
![image](https://github.com/user-attachments/assets/dde55485-95f3-4f3a-832c-fc45100215f3)
- Created a App Registration group and added to the workspace as Admin (Tried contributor as well) 
- Inside the Tenant setting, The following permissions for Service Principal was enabled
![image](https://github.com/user-attachments/assets/0cea4fb3-94e7-4b56-b1a6-995d5d2f6d7b)
![image](https://github.com/user-attachments/assets/6e8d861c-6905-4b1d-8bb2-0fbe5f41742d)


- From the Framework execution side, the Service principal authorization was successful
- However, it failed in get workspace id operation with the below error. (At the time of 

![image](https://github.com/user-attachments/assets/137e8199-1056-4108-9163-0392fca37d85)

Reading from the documentation , understand that access to Fabric API through service principals are limited 
https://learn.microsoft.com/en-us/fabric/admin/metadata-scanning-enable-read-only-apis
cc: @insightgrantkrieger

**Comment by KRodriguez-Insight** [comment]
Update : Was able to create a account with non MFA (Exempted for 14 days) in own tenant, and was able to deploy and execute the frame work through GIT Actions 

![image](https://github.com/user-attachments/assets/eb6a551e-ccc6-4680-9735-09dfd943dffb)
![image](https://github.com/user-attachments/assets/e373f39d-7e08-4fac-96c4-e301515640b7)

This is on a test repository , will test and formalize the change
cc: @insightgrantkrieger

**Comment by KRodriguez-Insight** [comment]
Updated the documentation on the limitations on Service Principal
![image](https://github.com/user-attachments/assets/bec88e39-66dc-4944-ba1f-9abb9336aae4)

**Comment by KRodriguez-Insight** [comment]
The Git action has been created and tested in a separate repo on a test Tenant, However it is setup to run locally now., once the Test workspace is created, it will be enabled to run without switches.

cc: @insightgrantkrieger
