### ISSUE TITLE
Ability to create SQL Analytics endpoint views from models

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#148]
**Is your feature request related to a problem? Please describe.**
In the framework, when a model is instantiated as a View, it is currently created as a Spark view.
The requirement is to have the option to create a SQL endpoint view instead. 
This would require the generated notebook to connect to the SQL endpoint to run the create\alter statement.

**Describe the solution you'd like**
As above

**Describe alternatives you've considered**
Manually creating the view outside of the framework

**Additional context**
None

**Comment by insightgrantkrieger** [comment]
No longer required JP will create manually as its only to control access
