### ISSUE TITLE
A thread property exists in profile.yml this should be used when running the notebooks

### ISSUE THREAD

**Issue by insightgrantkrieger** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#15]
A thread property exists in profile.yml this should be used when running the notes books.
Note this property should dynamically replace the 5 below which can be found in the master notebooks:
    with ThreadPoolExecutor(max_workers=5) as executor:
        new_results = list(executor.map(execute_notebook, notebook_files1))

**Comment by insightgrantkrieger** [comment]
@jrampono  We have GenerateMasterNotebook in wrapper folder in generate_files.py and we have it in utils.py in fabricsparknb folder. We are now updating the wrapper flavour only. IS this correct?

**Comment by KRodriguez-Insight** [comment]
@jrampono , Do we need to consider any default value, if the thread property is not provided (Example : 0) or any high range

**Comment by insightgrantkrieger** [comment]
I would say the default should be 5 as it currently is

**Comment by KRodriguez-Insight** [comment]
@annstephyjose , Please find the thread validation conditions for testing
![image](https://github.com/user-attachments/assets/42c65a6e-39f3-4a03-8c9e-01fcfe78129b)

**Comment by insightgrantkrieger** [comment]
Completed and tested all good
