### ISSUE TITLE
Add in console display of master notebook execution results

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#150]

**Comment by jrampono** [comment]
![image](https://github.com/user-attachments/assets/24a3c207-c4cc-4277-9a6f-35a13cdf7b34)

**Comment by jrampono** [comment]
![image](https://github.com/user-attachments/assets/699d3a80-3dab-442b-ba12-af0d875c1551)

**Comment by jrampono** [comment]
![image](https://github.com/user-attachments/assets/0cbdc2b4-6712-4d78-ae48-50d5e3b71cef)

**Comment by insightgrantkrieger** [comment]
Completed
