### ISSUE TITLE
Bug - Thread property is getting assigned a  default value

### ISSUE THREAD

**Issue by KRodriguez-Insight** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#153]
Identified a bug, when the thread value is set between 5 (Low Range) to 19 (High Range) , A default value of 5 is getting assigned

**Comment by KRodriguez-Insight** [comment]
Issue : 
Profile.yml has Thread value set a 9 

![image](https://github.com/user-attachments/assets/bc6579a3-a0ec-4b66-bb50-5b8144bba06b)

But Notebook is generated as 5
![image](https://github.com/user-attachments/assets/8be8872a-6ddd-43c3-8b9b-ab8ec52ed0b2)

**Comment by insightgrantkrieger** [comment]
Done
