### ISSUE TITLE
Add a new switch to allow for setting default datalake by code rather than by notebook property

### ISSUE THREAD

**Issue by insightgrantkrieger** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#157]
Add a new switch to allow for setting default datalake by code rather than by notebook property. This is the %%configure cell

**Comment by cheinamann** [comment]
I have completed this task. When using the wrapper adding this config to the execution will remove the lakehouse from metadata and the code cells back in. This is not supported in high concurrency mode. --lakehouse-config="CODE"

**Comment by cheinamann** [comment]
This has been merged to dev
