### ISSUE TITLE
Remove items from the framework which are no longer required 

### ISSUE THREAD

**Issue by annstephyjose** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#163]
This feature includes the follows: 
1. Identify and compile a list of outdated items from our current framework that are no longer needed 
Eg: import notebooks and the dev-requirements.txt file.
2. Review the compiled list with Grant.
3. Remove the identified items.

**Comment by amrhelmyinight** [comment]
1- Compare C:\Work\FA\FA_RemvoeItems\APAC-Capability-DAI-DbtFabricSparkNb\dbt\include\fabricsparknb\notebooks\metadata_extract
 with the obsolete metadata_extract in "C:\Work\FA\FA_RemvoeItems\APAC-Capability-DAI-DbtFabricSparkNb\dbt\include\fabricsparknb\" if not needed then we can delete

2- under C:\Work\FA\FA_RemvoeItems\APAC-Capability-DAI-DbtFabricSparkNb\dbt_AmrDev\target\notebooks  remove the generation  code of "import_dbt_AmrDev_notebook" 
3- under C:\Work\FA\FA_RemvoeItems\APAC-Capability-DAI-DbtFabricSparkNb\dbt_AmrDev\target\notebooks_fabric_py  remove the generation  code of "import_dbt_AmrDev_notebook" 
4- remove "dev-requirements.txt" file
