### ISSUE TITLE
Metadata Extract notebook seems to always be uploaded even though the hash has not changed. 

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#168]
![image](https://github.com/user-attachments/assets/bed8ef3a-47dc-4be4-a8c8-f8b63e90844b)

![image](https://github.com/user-attachments/assets/6a488c84-3a12-4f7a-989c-b3360df39dee)

-------------------------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------------------------

![image](https://github.com/user-attachments/assets/b654dd7d-d032-47b5-afea-e23dd4f2a4b8)

**Comment by JacquesInsight** [comment]
![image](https://github.com/user-attachments/assets/59768a58-54d2-4dad-b8a7-6c0d6c7102b1)

**Comment by JacquesInsight** [comment]
@jrampono Can you provide the steps to replicate. I am unable to reproduce in the dev deployment process. During testing I modified the metadata notebook and added a comment, without changing the hash and the notebook was not overwritten.

Is it a specific branch that I could maybe test with where you encountered the issue.
