### ISSUE TITLE
Capability to generate notebooks that can be checked into Fabric version control

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#24]
Framework generates .ipynb files that can be imported into Fabric, but when these files are version controlled the are saved as .py files in a folder:

![image](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/assets/98132332/895fe0f7-fff4-4897-972f-72c34ae070cb)

Ideally I'd like the process to be:
1. generate notebook
2. copy notebook to local version controlled folder
3. check notebook into version control
4. refresh Fabric workspace and notebook is available

If this isn't possible, preference would be to (manually) import notebook into Fabric rather than import via lakehouse

**Comment by annstephyjose** [comment]
I've tested the change #24 in the feature branch, which resulted in Python files being generated under the 'notebooks_fabric_py' folder. However, I couldn't verify the synchronization with devops-fabric-git due to permissions limitations using my fabric profile. I discussed this with Grant and confirmed the results on his system.

**Comment by insightgrantkrieger** [comment]
Note: Updated work around steps:
Disconnect repo 
Delete all files in repo folder (You do not need to delete the folder)
Then reconnect to repo same repo folder and all good

**Comment by insightgrantkrieger** [comment]
APIUpsertNotebooks has also been added which easily updates notebooks directory to the API end point

**Comment by insightgrantkrieger** [comment]
Aligned to Dev branch and John's latest changes for pip install

**Comment by insightgrantkrieger** [comment]
This is covered by api update. File structure has been utilized for that
