### ISSUE TITLE
Logging to delta

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#27]
Changing logging from a file in the lakehouse (which is overwritten) to appending to a delta table in a defined lakehouse

**Comment by cheinamann** [comment]
Added the import json back to the notebooks. This went missing during merging.

**Comment by cheinamann** [comment]
I have fixed the bug by adding the lakehouse where the tables are recorded. This has been tested by me. I found another bug where if there is a failure in the final step of the ETL no errors are returned and the batch is closed. Now if an error is found the batch will not close. This can now be tested by Ann before being merged. Please use branch "feature/logtodeltabugfix"
