### ISSUE TITLE
Possible bug - Append 

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#41]
When using a incremental_strategy="append" the notebook doesn't generate properly - the select statement does not contain any columns:

![image](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/assets/98132332/91e45443-5bdd-4b5f-96e6-0a770f71f2c5)
![image](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/assets/98132332/1692fb91-cb22-4689-a4a1-01f2cd05f4d1)

Generated notebook:

![image](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/assets/98132332/a60d5089-9ba7-4b6a-8d18-98d9cc9269ee)

![image](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/assets/98132332/f04bd360-77fc-461a-9bc6-a10ad4219389)

**Note:** Final select is incorrect in notebook (no columns or *)

**Comment by annstephyjose** [comment]
tested this fix in the dev branch and all good to go. @insightgrantkrieger @KRodriguez-Insight you can close this now
