### ISSUE TITLE
Create 'before' and 'after' stubs in notebook

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#42]
We need the ability to run bespoke (ie non framework generated) notebooks at the start and end of a model notebook:

If the model is called model.myproject.mymodel.ipynb, there should be two notebook executions calls:

Before executing the SQL Statements:

	msspark.notebook.run("model.myproject.mymodel.before.ipynb")

After executing the SQL Statements:

	msspark.notebook.run("model.myproject.mymodel.after.ipynb")

We'd need to either check that the notebook exists beforehand or always generate empty notebooks for the above.

**Comment by JacquesInsight** [comment]
1. Add Section before Executing the Module Portion
2. Add Section after the Module Execution
3. Update Documentation and add section to detail the before and after execution

Code section sample to use as base:
# Import the necessary modules
from pyspark.sql import SparkSession

# Create a Spark session
spark = SparkSession.builder.getOrCreate()

# Check if the notebook exists
notebook_path = "/path/to/your/notebook"
dbutils = spark._jvm.dbutils
if dbutils.fs.ls(notebook_path):
    print("Notebook exists. Proceed with execution.")
    # Execute the notebook
    dbutils.notebook.run(notebook_path)
else:
    print("Notebook does not exist.")

**Comment by annstephyjose** [comment]
included in v0.6
