### ISSUE TITLE
Add section in user guide that describes options for code migration / promotion from one workspace to another

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#55]
Create a section in the documentation similar to this blog article: 

[https://data-marc.com/2024/07/09/fabric-ci-cd-with-git-deployment-and-release-strategies/](https://data-marc.com/2024/07/09/fabric-ci-cd-with-git-deployment-and-release-strategies/)

**Comment by KGaind-Insight** [comment]
Added the section in the feature branch for release next week.
