### ISSUE TITLE
Enhance Metadata Hash Check so that it is optional with three levels

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#61]
Levels: 
1) Error - As is
2) Warn
3) Bypassed - No metarefresh or has check done

**Comment by jrampono** [comment]
To assign to Amr

**Comment by insightgrantkrieger** [comment]
@jrampono where would you like the options set?

**Comment by jrampono** [comment]
> @jrampono where would you like the options set?

In the wrapper options. You can use log-level as an example

**Comment by JacquesInsight** [comment]
1. Create new class for HashCheck_Levels
2. Add HashCheck_Levels list to main.py
3. Add HashCheck_Levels option to def "run_all" in main.py
4. Pass new option to GeneratePostDbtScripts call
5. Update GeneratePostDbtScripts def in wrapper.py
6. Pass new option to GenerateMasterNotebook in wrapper.py
7. Update GenerateMasterNotebook def in generate_files.py
8. Update generate_files.py and "import dbt_wrapper.HashCheck_Levels"
9. Add a parameter to the "template.render" command for master_notebook.ipynb
10. Add parameter/variable to the master_notebook.ipynb template to cater for the

**Comment by jrampono** [comment]
> [@jrampono](https://github.com/jrampono) Does this look like the right approach?
> 
> 1. Create new class for HashCheck_Levels
> 2. Add HashCheck_Levels list to main.py
> 3. Add HashCheck_Levels option to def "run_all" in main.py
> 4. Pass new option to GeneratePostDbtScripts call
> 5. Update GeneratePostDbtScripts def in wrapper.py
> 6. Pass new option to GenerateMasterNotebook in wrapper.py
> 7. Update GenerateMasterNotebook def in generate_files.py
> 8. Update generate_files.py and "import dbt_wrapper.HashCheck_Levels"
> 9. Add a parameter to the "template.render" command for master_notebook.ipynb
> 10. Add parameter/variable to the master_notebook.ipynb template to cater for the

Yup looks good to me @JacquesInsight

**Comment by insightgrantkrieger** [comment]
Completed
