### ISSUE TITLE
Edit timeout on call_childnotebook function in master notebook template to max allowable

### ISSUE THREAD

**Issue by insightgrantkrieger** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#65]
Long running notebooks are causing a timeout.Solution is to set increased configurable timeout on mssparkutils.notebook.run() calls.Example mssparkutils.notebook.run("metadata_extract") fails with timeout error. When we inject mssparkutils.notebook.run("metadata_extract",600) all is fine. A notebook timeout configuration should be set.

**Comment by cheinamann** [comment]
I have created the pull request for this issue. Use the option to set the timeout value else default is 1800:
dbt_wrapper run-all my_project --notebook-timeout=2100

**Comment by annstephyjose** [comment]
tested and working fine
