### ISSUE TITLE
Add documentation documentation regarding High Concurrency Sessions

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#77]

**Comment by jrampono** [comment]
To assign to Amr

**Comment by amrhelmyinight** [comment]
Done
![Screenshot 2024-07-31 163839](https://github.com/user-attachments/assets/86a5b6c8-49e2-48ee-8f82-272bcbf774fb)

**Comment by annstephyjose** [comment]
High concurrency sessions will be handled by [#78](https://github.com/Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb/issues/78)
