### ISSUE TITLE
Parameter cells not being persisted when using api method to upload notebooks

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#85]

**Comment by insightgrantkrieger** [comment]
Fixed by adding support for this.The following method fixes this and has been given to John to implement
[pyfileparameters.txt](https://github.com/user-attachments/files/16326826/pyfileparameters.txt)

**Comment by insightgrantkrieger** [comment]
Completed and released
