### ISSUE TITLE
Add hash file to track notebook changes and allow incremental upload of generated notebooks

### ISSUE THREAD

**Issue by jrampono** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#87]
Add hash file to track notebook changes and allow incremental upload of generated notebooks

**Comment by JacquesInsight** [comment]
step 1: download all the notebooks
Create hash over notebooks
Compare hash where notebook name is the same or not deployed yet
Only deploy changed or "missing" notebooks

**Comment by jrampono** [comment]
> @jrampono please confirm the following. step 1: download all the notebooks step 2: Create hash over notebooks step 3: Compare hash where notebook name is the same or not deployed yet step 4: Only deploy changed or "missing" notebooks

Hmmm, I'm thinking that the download all notebooks part of the process could become just as much of an issue as the upload in terms of a bottleneck. What if we do this: 


1. When we create the notebooks in the upload process could we add a content hash to the end of the description? Maybe something like <hash>6fda453d8f2dc927f323232732873e87887c5159e9973bd9f4c5c5a791bc62fc</hash>
2. Before upload we check List notebooks and store in local json

Here are the attributes returned: 
![image](https://github.com/user-attachments/assets/d9c6b7e2-c301-4f60-b96f-f61128f45158)

3. Then during any subsequent notebook upload we check for a hash in the description, if there isnt one we always upload the notebook, if there is we compare with the content hash of the generated notebook and if different we upload

**Comment by JacquesInsight** [comment]
Step 1: create hash across the definition of the notebook and add to the description
Step 2: loop through the list of notebooks and check if the hash exists in the description
Step 3: if not exist upload

This will all be done in the "loop process" of the notebook generation.

![image](https://github.com/user-attachments/assets/4fd5b8f9-1e8b-410c-b377-e832b6701fe3)

**Comment by JacquesInsight** [comment]
Branch: Feature/NotebookHash#87JM

Ready for testing

**Comment by insightgrantkrieger** [comment]
Completed and tested all good
