### ISSUE TITLE
Debugging info doesn't appear to work

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#96]
**Describe the bug**
When encountering a problem (like issue #94), the debug info and logs do not provide much assistance in solving the problem

**To Reproduce**
See issue #94

**Expected behavior**
Debug info and log that will assist with resolving the issue

**Screenshots**

![image](https://github.com/user-attachments/assets/643ec88c-c982-43a6-a5a0-1b3b013b2d1d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 1.7.0 

**Additional context**
Using new 'User version' and discussed with Grant

**Comment by jp-vanheerden** [comment]
After further digging I realised that logging on the project level does work (logs\dbt.log). Issue can be cancelled

**Comment by insightgrantkrieger** [comment]
Opened issue in error will close
