### ISSUE TITLE
Schema compare between environments & generate change script

### ISSUE THREAD

**Issue by jp-vanheerden** [Insight-Services-APAC/APAC-Capability-DAI-DbtFabricSparkNb#99]
**Is your feature request related to a problem? Please describe.**
When promoting between environments (eg Dev and UAT), tables may be different or not exist in the second environment. The process of updating the tables is currently manual and it would be useful to have a process that compares the table definitions between two environments and generates a script to change the second environment to match the first environment.

**Describe the solution you'd like**
Process that:
1. Gets the table definitions for the first environment
2. Gets the table definitions for the second environment
3. Compares the table definitions and generates DDL statements to handle changes
4. Where changes cannot be handled automatically, a placeholder is added
5. Generate a notebook that can be run in the second environment

**Describe alternatives you've considered**
There may be utilities available in the community that can be re-used

**Additional context**
N/A

**Comment by avinvagel** [comment]
Two new notebooks added to: `dbt\include\fabricsparknb\notebooks`:

1. `compare_notebook'` 
2. `util_BuildMetadata`

Two new commands added:
1. buildcomparemetadata: which will execute the util_buildmetadata notebook in the environment configured
Arguments: 
- dbt_project_dir: The path to the dbt_project directory. If left blank it will use the current directory
- source: Source environment name from profile.yml
- target: Target environment name from profile.yml
- dbt_profiles_dir: The path to the dbt_profile directory. If left blank it will use the users home directory followed by .dbt.

2. compare:     This command will generate compare two environments lakehouses. Generated notebooks will be uploaed to the 'target' environment configured in the 'profile.yml' file.
- dbt_project_dir: The path to the dbt_project directory. If left blank it will use the current directory
- source: Source environment name from profile.yml
- target: Target environment name from profile.yml
- dbt_profiles_dir: The path to the dbt_profile directory. If left blank it will use the users home directory followed by .dbt.

**Comment by avinvagel** [comment]
New items required in the profile.yml file to specify the other environments to compare to:

![image](https://github.com/user-attachments/assets/3896e9da-6f46-4868-8da3-5cdb2152aaca)

**Comment by insightgrantkrieger** [comment]
Review session setup for tuesday with 13th August to confirm all happy

**Comment by annstephyjose** [comment]
Created #185 and #186 to address the further enhancements
